
spring:
  http:
    encoding:
      charset: UTF-8
    enabled: true
    force: true

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  application:
    name: live-center

  cloud:
    inetutils:
      use-only-site-local-interfaces: true
  profiles:
    active: dev

  messages:
    basename: i18n/messages


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

page:
  page_size: 100
  page_num: 1
  order_by: "create_time desc"

server:
  port: 8089



