#eureka:
#  client:
#    filter-only-up-instances: true
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://192.168.1.138:9090/eureka
#
# instance:
#   prefer-ip-address: true
#   lease-renewal-interval-in-seconds: 5
#   lease-expiration-duration-in-seconds: 10
#   instance-id: ${spring.cloud.client.ip-address}:${server.port}

spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.138:3306/resourcecenter?useUnicode=true&characterEncoding=utf8
    type: com.alibaba.druid.pool.DruidDataSource
  #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filter.commons-log.connection-logger-name: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000

ffmpeg:
  path: ./ffmpeg/win/
  defaultpathEnable: true
  size: 100
  debug: true
  issyspath: false
  defaultaudio: default/audio.aac
  defaultimage: default/video.jpg
  vcodec: libx264 -coder 1 -flags +loop -cmp +chroma -subq 10 -qcomp 0.6 -qmin 10  -r 15 -g 15
  acodec: aac